"""empty message

Revision ID: 3ad9d3182a74
Revises: aaf8cc1a638b
Create Date: 2018-10-16 00:09:14.482407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad9d3182a74'
down_revision = 'aaf8cc1a638b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('sender', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email', 'user', ['sender'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.drop_column('email', 'sender')
    # ### end Alembic commands ###
