"""empty message

Revision ID: b7ccff5b0df7
Revises: 3ad9d3182a74
Create Date: 2018-10-16 00:16:36.304424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ccff5b0df7'
down_revision = '3ad9d3182a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('recipient', table_name='email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('recipient', 'email', ['recipient'], unique=True)
    # ### end Alembic commands ###
